### ISSUE TITLE
Can't be compiled on Ubuntu.

### ISSUE THREAD

**Issue by ivegotasthma** [thestinger/termite#370]
Hello,

On my Arch machine it's provided by the package manager.  
On Ubuntu on the other hand it's very difficult, there is [this](https://github.com/Corwind/termite-install) but it's out of date, even with changes from the PRs applied. I have tried to make `termite` compile for 2,5h to no avail. I can compile the `vte3-ng` library by taking a look at the PKGBUILD that's in the Arch package, but `termite` itself doesn't compile.

**Comment by thestinger** [comment]
I can be compiled on Ubuntu, there's no bug.

**Comment by ivegotasthma** [comment]
Can you give some instructions on how to do it?

**Comment by thestinger** [comment]
I don't use Debian/Ubuntu, so I can't.

**Comment by jelly** [comment]
That script is probably wrong, and installed an old version of vte3-ng. But posting actual errors would help a lot.

**Comment by gambhiro** [comment]
I followed @jelly 's tips and successfully built vte-ng and termite. Shouldn't this be in the Readme?

**Comment by thestinger** [comment]
No, I'm not going to have distribution-specific instructions, especially for distributions that I dislike.

**Comment by gambhiro** [comment]
@thestinger Nonetheless, thanks for this terminal, I'm enjoying using it. urxvt was good, but this is a relief.

**Comment by alanctkc** [comment]
For others who come across the issue, here's an ansible playbook with all the steps I used to successfully install termite locally (maintained [here](https://github.com/alanctkc/dotfiles/blob/master/playbooks/roles/termite/tasks/main.yml) but copied for posterity in case it goes away):

```yaml
---
- name: Clone vte-ng
  become: yes
  git: repo=https://github.com/thestinger/vte-ng.git
       accept_hostkey=true
       dest=/usr/local/src/vte-ng

- name: Install vte-ng dependencies
  become: yes
  apt: name={{item}}
       state=present
  with_items:
    - autoconf
    - libgtk-3-dev
    - libpango1.0-dev
    - libgnutls-dev
    - libglib2.0-dev
    - libgirepository1.0-dev
    - valac
    - libxml2-utils
    - gtk-doc-tools
    - gperf

- name: Configure vte-ng
  become: yes
  command: ./autogen.sh
  args:
    chdir: /usr/local/src/vte-ng
    creates: /usr/local/src/vte-ng/Makefile

- name: Build vte-ng
  become: yes
  command: make
  args:
    chdir: /usr/local/src/vte-ng
    creates: /usr/local/src/vte-ng/src/vte-2.91

- name: Install vte-ng
  become: yes
  command: checkinstall --pkgname vte-ng --pkgversion 2.91
  args:
    chdir: /usr/local/src/vte-ng
    creates: /usr/local/bin/vte-2.91

- name: Clone termite
  become: yes
  git: repo=https://github.com/thestinger/termite.git
       accept_hostkey=true
       dest=/usr/local/src/termite

- name: Build termite
  become: yes
  command: make
  args:
    chdir: /usr/local/src/termite
    creates: /usr/local/src/termite/termite

- name: Intall termite
  become: yes
  command: checkinstall
  args:
    chdir: /usr/local/src/termite
    creates: /usr/local/bin/termite

- name: Set termite as default terminal
  become: yes
  alternatives: name=x-terminal-emulator
                path=/usr/local/bin/termite
```
