### ISSUE TITLE
Gtk Scrollbar not themeable via gtk3 style css

### ISSUE THREAD

**Issue by anthraxx** [thestinger/termite#557]
I did not manage to find any way to style the scrollbar via the gtk3 style css (same one that is used to add padding to termite).
It looks like there is something missing in the code that allows to style the scrollbar.

**Comment by jeremejevs** [comment]
Just styled the scrollbar, worked fine. Here's my CSS (copy of [Spacegray Eighties](https://github.com/kkga/spacegray#spacegray-eighties)):

```css
/* ~/.config/gtk-3.0/gtk.css */

scrollbar {
  background-color: #262626;
}

slider {
  background-color: #3c3c3c;
  border-radius: 0;
  border: none;
  margin: 0;
  min-height: 12px;
  min-width: 12px;
}
```

[Default Adwaita stylesheet](https://github.com/GNOME/gtk/blob/ac97d2be0c8c5d81e0fc0572b0966d71e6faaadb/gtk/theme/Adwaita/_common.scss#L2451), for the reference.
