### ISSUE TITLE
How can I change foreground color in the search box?

### ISSUE THREAD

**Issue by mnacamura** [thestinger/termite#731]
I mean the search box that appears after pressing `Ctrl-Shift-Space` then `/`.

I've found that putting the following lines in `~/.config/gtk-3.0/gtk.css` works:
```css
overlay > entry {
    color: red; /* for example */
}
```
However, it may affect not only termite but also the other GTK+ applications. My question is how to narrow the scope to termite only.
